### ISSUE TITLE
google maps

### ISSUE THREAD

**Issue by st4ll1** [ihanli/sbicktAndroid#5]
google maps does not appear on samsung galaxy s with android 2.2

**Comment by ihanli** [comment]
http://code.google.com/intl/de-DE/android/add-ons/google-apis/mapkey.html

http://stackoverflow.com/questions/2997348/cant-find-the-android-keytool

create a debugger mapkey and register for an api-key (send it to me). i will then rebuild the apk.

**Comment by st4ll1** [comment]
map works, but tester have to create a debugger mapkey, enter the key in the sourcecode and compile by himself.
